name: Maven CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Tests
        run: mvn test

      - name: Upload build artifacts (JAR/WAR)
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: target/*.jar
